INFO - 2024-03-28 04:07:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:09:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:09:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:09:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:09:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:09:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:10:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:10:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:10:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:10:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:10:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 04:15:22 --> mysqli_sql_exception: Can't create table `crud_data`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `a...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `a...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `a...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `a...')
#4 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Database\Migrations\2017-11-20-223112_create_auth_tables.php(65): CodeIgniter\Database\Forge->createTable('auth_tokens', true)
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): Myth\Auth\Database\Migrations\CreateAuthTables->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2024-03-28 04:20:04 --> mysqli_sql_exception: Can't create table `crud_data`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `a...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `a...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `a...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `a...')
#4 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Database\Migrations\2017-11-20-223112_create_auth_tables.php(65): CodeIgniter\Database\Forge->createTable('auth_tokens', true)
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): Myth\Auth\Database\Migrations\CreateAuthTables->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
INFO - 2024-03-28 04:21:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 04:22:20 --> mysqli_sql_exception: Can't create table `crud_data`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `a...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `a...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `a...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `a...')
#4 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Database\Migrations\2017-11-20-223112_create_auth_tables.php(65): CodeIgniter\Database\Forge->createTable('auth_tokens', true)
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): Myth\Auth\Database\Migrations\CreateAuthTables->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
INFO - 2024-03-28 04:51:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:51:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:58:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:58:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:59:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 04:59:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 12:55:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 12:55:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 12:55:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 12:56:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 12:56:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:13:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:14:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:14:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:14:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:15:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:15:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:15:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:15:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:15:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:16:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:24:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:25:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:25:20 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'crud_data', 3306, '', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', Array, Array)
#7 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', Array, Array)
#6 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-28 13:25:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(152): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:25:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:25:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:25:51 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'crud_data', 3306, '', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', Array, Array)
#7 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', Array, Array)
#6 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-28 13:25:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', [...], [...])
 6 SYSTEMPATH\Controller.php(152): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:27:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:27:24 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'crud_data', 3306, '', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', Array, Array)
#7 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', Array, Array)
#6 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-28 13:27:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', [...], [...])
 6 SYSTEMPATH\Controller.php(152): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:27:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:27:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:27:56 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'crud_data', 3306, '', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', Array, Array)
#7 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', Array, Array)
#6 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-28 13:27:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', [...], [...])
 6 SYSTEMPATH\Controller.php(152): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:28:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:28:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:28:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:28:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:28:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:28:48 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'crud_data', 3306, '', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', Array, Array)
#7 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', Array, Array)
#6 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-28 13:28:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', [...], [...])
 6 SYSTEMPATH\Controller.php(152): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:28:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:31:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:31:22 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'crud_data', 3306, '', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', Array, Array)
#7 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', Array, Array)
#6 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-28 13:31:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('fahmil', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'fahmil', [...], [...])
 6 SYSTEMPATH\Controller.php(152): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:31:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:31:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:32:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:32:18 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'crud_data', 3306, '', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', Array, Array)
#7 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', Array, Array)
#6 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-28 13:32:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(152): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:34:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:34:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:34:30 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'crud_data', 3306, '', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', Array, Array)
#7 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', Array, Array)
#6 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-28 13:34:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(152): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:34:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:34:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:34:52 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'crud_data', 3306, '', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', Array, NULL, 'username')
#6 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', Array, Array)
#7 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codenighter\system\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', Array, NULL, 'username')
#5 C:\xampp\htdocs\codenighter\system\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', Array, Array)
#6 C:\xampp\htdocs\codenighter\system\Controller.php(152): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-28 13:34:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(227): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(328): CodeIgniter\Validation\StrictRules\Rules->is_unique('Admin', 'username', [...], null, 'username')
 5 SYSTEMPATH\Validation\Validation.php(200): CodeIgniter\Validation\Validation->processRules('username', 'username', 'Admin', [...], [...])
 6 SYSTEMPATH\Controller.php(152): CodeIgniter\Validation\Validation->run()
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(154): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:34:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:35:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:35:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:35:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:35:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:35:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:35:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:35:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:35:42 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'crud_data', 3306, '', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\codenighter\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\codenighter\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#7 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#8 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptLogin()
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-03-28 13:35:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
AND `users`.`deleted_at` IS NULL
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFirst()
 5 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:35:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:41:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:41:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:41:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:41:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:41:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:41:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:42:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:42:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:44:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:44:31 --> mysqli_sql_exception: Unknown column 'password_hash' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\codenighter\system\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-03-28 13:44:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 6 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 7 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 13:44:31 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$L0xVjS1hj4jjVB5zaNMhsesADkZ7rsGDEOhjOSfb1pA1LdMFpYhtu\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'ffc99ae33b5c803b4716133834067ff4\', \'2024-03-28 13:44:31\', \'2024-03-28 13:44:31\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$L0xVjS1hj4jjVB5zaNMhsesADkZ7rsGDEOhjOSfb1pA1LdMFpYhtu\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'ffc99ae33b5c803b4716133834067ff4\', \'2024-03-28 13:44:31\', \'2024-03-28 13:44:31\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 8 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 9 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 13:44:31 --> [Caused by] mysqli_sql_exception: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$L0xVjS1hj4jjVB5zaNMhsesADkZ7rsGDEOhjOSfb1pA1LdMFpYhtu\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'ffc99ae33b5c803b4716133834067ff4\', \'2024-03-28 13:44:31\', \'2024-03-28 13:44:31\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$L0xVjS1hj4jjVB5zaNMhsesADkZ7rsGDEOhjOSfb1pA1LdMFpYhtu\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'ffc99ae33b5c803b4716133834067ff4\', \'2024-03-28 13:44:31\', \'2024-03-28 13:44:31\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$L0xVjS1hj4jjVB5zaNMhsesADkZ7rsGDEOhjOSfb1pA1LdMFpYhtu\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'ffc99ae33b5c803b4716133834067ff4\', \'2024-03-28 13:44:31\', \'2024-03-28 13:44:31\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 9 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
10 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:45:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:46:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:47:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:47:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:48:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:48:14 --> mysqli_sql_exception: Unknown column 'password_hash' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\codenighter\system\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-03-28 13:48:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 6 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 7 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 13:48:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$KNmaFVjVVh8ZAMQEh4NLy..PM3SCtYxayjrKNSJJApGiuyF7ASYTa\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'bfe1d920ea02617bc554c57420108a8a\', \'2024-03-28 13:48:14\', \'2024-03-28 13:48:14\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$KNmaFVjVVh8ZAMQEh4NLy..PM3SCtYxayjrKNSJJApGiuyF7ASYTa\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'bfe1d920ea02617bc554c57420108a8a\', \'2024-03-28 13:48:14\', \'2024-03-28 13:48:14\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 8 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 9 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 13:48:14 --> [Caused by] mysqli_sql_exception: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$KNmaFVjVVh8ZAMQEh4NLy..PM3SCtYxayjrKNSJJApGiuyF7ASYTa\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'bfe1d920ea02617bc554c57420108a8a\', \'2024-03-28 13:48:14\', \'2024-03-28 13:48:14\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$KNmaFVjVVh8ZAMQEh4NLy..PM3SCtYxayjrKNSJJApGiuyF7ASYTa\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'bfe1d920ea02617bc554c57420108a8a\', \'2024-03-28 13:48:14\', \'2024-03-28 13:48:14\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$KNmaFVjVVh8ZAMQEh4NLy..PM3SCtYxayjrKNSJJApGiuyF7ASYTa\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'bfe1d920ea02617bc554c57420108a8a\', \'2024-03-28 13:48:14\', \'2024-03-28 13:48:14\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 9 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
10 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 13:48:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:49:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:49:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:49:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:49:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:49:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 13:50:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 13:50:10 --> mysqli_sql_exception: Unknown column 'password_hash' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\codenighter\system\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-03-28 13:50:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 6 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 7 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 13:50:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$yhWm5AiogoDnfBI11rpuuOGLrtG3mXfNqCNqiwSphwh0IXxNepQem\', NULL, NULL, NULL, \'ulumf3701@gmail.com\', \'Admin\', \'edf4deee579b3e96fb3828a827f2b8dd\', \'2024-03-28 13:50:10\', \'2024-03-28 13:50:10\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$yhWm5AiogoDnfBI11rpuuOGLrtG3mXfNqCNqiwSphwh0IXxNepQem\', NULL, NULL, NULL, \'ulumf3701@gmail.com\', \'Admin\', \'edf4deee579b3e96fb3828a827f2b8dd\', \'2024-03-28 13:50:10\', \'2024-03-28 13:50:10\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 8 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 9 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 13:50:10 --> [Caused by] mysqli_sql_exception: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$yhWm5AiogoDnfBI11rpuuOGLrtG3mXfNqCNqiwSphwh0IXxNepQem\', NULL, NULL, NULL, \'ulumf3701@gmail.com\', \'Admin\', \'edf4deee579b3e96fb3828a827f2b8dd\', \'2024-03-28 13:50:10\', \'2024-03-28 13:50:10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$yhWm5AiogoDnfBI11rpuuOGLrtG3mXfNqCNqiwSphwh0IXxNepQem\', NULL, NULL, NULL, \'ulumf3701@gmail.com\', \'Admin\', \'edf4deee579b3e96fb3828a827f2b8dd\', \'2024-03-28 13:50:10\', \'2024-03-28 13:50:10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$yhWm5AiogoDnfBI11rpuuOGLrtG3mXfNqCNqiwSphwh0IXxNepQem\', NULL, NULL, NULL, \'ulumf3701@gmail.com\', \'Admin\', \'edf4deee579b3e96fb3828a827f2b8dd\', \'2024-03-28 13:50:10\', \'2024-03-28 13:50:10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 9 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
10 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 14:35:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 14:35:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 14:35:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 14:35:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 14:35:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 14:35:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 14:36:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 14:36:24 --> mysqli_sql_exception: Unknown column 'password_hash' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\codenighter\system\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-03-28 14:36:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 6 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 7 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 14:36:24 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$WHTtKhiOIOxcI5DPMpGUL.ZL149FKhVBQZT8UhO/MXcYqaN0FX2OO\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'8e1b25dcfed49644de67027dd5e70615\', \'2024-03-28 14:36:24\', \'2024-03-28 14:36:24\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$WHTtKhiOIOxcI5DPMpGUL.ZL149FKhVBQZT8UhO/MXcYqaN0FX2OO\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'8e1b25dcfed49644de67027dd5e70615\', \'2024-03-28 14:36:24\', \'2024-03-28 14:36:24\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 8 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 9 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 14:36:24 --> [Caused by] mysqli_sql_exception: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$WHTtKhiOIOxcI5DPMpGUL.ZL149FKhVBQZT8UhO/MXcYqaN0FX2OO\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'8e1b25dcfed49644de67027dd5e70615\', \'2024-03-28 14:36:24\', \'2024-03-28 14:36:24\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$WHTtKhiOIOxcI5DPMpGUL.ZL149FKhVBQZT8UhO/MXcYqaN0FX2OO\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'8e1b25dcfed49644de67027dd5e70615\', \'2024-03-28 14:36:24\', \'2024-03-28 14:36:24\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$WHTtKhiOIOxcI5DPMpGUL.ZL149FKhVBQZT8UhO/MXcYqaN0FX2OO\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'8e1b25dcfed49644de67027dd5e70615\', \'2024-03-28 14:36:24\', \'2024-03-28 14:36:24\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 9 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
10 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
ERROR - 2024-03-28 14:43:57 --> mysqli_sql_exception: Can't create table `crud_data`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `a...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `a...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `a...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `a...')
#4 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Database\Migrations\2017-11-20-223112_create_auth_tables.php(65): CodeIgniter\Database\Forge->createTable('auth_tokens', true)
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): Myth\Auth\Database\Migrations\CreateAuthTables->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
INFO - 2024-03-28 14:44:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 14:44:44 --> mysqli_sql_exception: Unknown column 'password_hash' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\codenighter\system\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-03-28 14:44:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 6 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 7 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 14:44:44 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$qxfhpSzsR.NH2sN.BGqDo.WbpjDpbTTUb7ueE9uRJ7D4KJNiJ6MD.\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'acc445cefcedbba2fd2f0919a1da17d5\', \'2024-03-28 14:44:44\', \'2024-03-28 14:44:44\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$qxfhpSzsR.NH2sN.BGqDo.WbpjDpbTTUb7ueE9uRJ7D4KJNiJ6MD.\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'acc445cefcedbba2fd2f0919a1da17d5\', \'2024-03-28 14:44:44\', \'2024-03-28 14:44:44\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 8 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 9 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 14:44:44 --> [Caused by] mysqli_sql_exception: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$qxfhpSzsR.NH2sN.BGqDo.WbpjDpbTTUb7ueE9uRJ7D4KJNiJ6MD.\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'acc445cefcedbba2fd2f0919a1da17d5\', \'2024-03-28 14:44:44\', \'2024-03-28 14:44:44\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$qxfhpSzsR.NH2sN.BGqDo.WbpjDpbTTUb7ueE9uRJ7D4KJNiJ6MD.\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'acc445cefcedbba2fd2f0919a1da17d5\', \'2024-03-28 14:44:44\', \'2024-03-28 14:44:44\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$qxfhpSzsR.NH2sN.BGqDo.WbpjDpbTTUb7ueE9uRJ7D4KJNiJ6MD.\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'acc445cefcedbba2fd2f0919a1da17d5\', \'2024-03-28 14:44:44\', \'2024-03-28 14:44:44\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 9 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
10 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 14:44:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 14:44:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 14:44:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 14:45:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 14:45:54 --> mysqli_sql_exception: Unknown column 'password_hash' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\codenighter\system\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-03-28 14:45:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 6 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 7 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 14:45:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$.cF8AqjcK2VFbE6Zvrc.LeD/mJKZZfYbR/lnSXngfGttFGfXGMZO2\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'886999147b8d1af9b8aa12d7c4089fe4\', \'2024-03-28 14:45:54\', \'2024-03-28 14:45:54\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$.cF8AqjcK2VFbE6Zvrc.LeD/mJKZZfYbR/lnSXngfGttFGfXGMZO2\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'886999147b8d1af9b8aa12d7c4089fe4\', \'2024-03-28 14:45:54\', \'2024-03-28 14:45:54\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 8 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 9 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 14:45:54 --> [Caused by] mysqli_sql_exception: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$.cF8AqjcK2VFbE6Zvrc.LeD/mJKZZfYbR/lnSXngfGttFGfXGMZO2\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'886999147b8d1af9b8aa12d7c4089fe4\', \'2024-03-28 14:45:54\', \'2024-03-28 14:45:54\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$.cF8AqjcK2VFbE6Zvrc.LeD/mJKZZfYbR/lnSXngfGttFGfXGMZO2\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'886999147b8d1af9b8aa12d7c4089fe4\', \'2024-03-28 14:45:54\', \'2024-03-28 14:45:54\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$.cF8AqjcK2VFbE6Zvrc.LeD/mJKZZfYbR/lnSXngfGttFGfXGMZO2\', NULL, NULL, NULL, \'fahmilulum36@gmail.com\', \'Admin\', \'886999147b8d1af9b8aa12d7c4089fe4\', \'2024-03-28 14:45:54\', \'2024-03-28 14:45:54\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 9 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
10 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
ERROR - 2024-03-28 15:22:05 --> mysqli_sql_exception: Can't create table `crud_data`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `a...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `a...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `a...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `a...')
#4 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Database\Migrations\2017-11-20-223112_create_auth_tables.php(65): CodeIgniter\Database\Forge->createTable('auth_tokens', true)
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): Myth\Auth\Database\Migrations\CreateAuthTables->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2024-03-28 15:22:58 --> mysqli_sql_exception: Can't create table `crud_data`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `a...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `a...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `a...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `a...')
#4 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Database\Migrations\2017-11-20-223112_create_auth_tables.php(65): CodeIgniter\Database\Forge->createTable('auth_tokens', true)
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): Myth\Auth\Database\Migrations\CreateAuthTables->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2024-03-28 15:24:23 --> mysqli_sql_exception: Can't create table `crud_data`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `a...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `a...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `a...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `a...')
#4 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Database\Migrations\2017-11-20-223112_create_auth_tables.php(65): CodeIgniter\Database\Forge->createTable('auth_tokens', true)
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): Myth\Auth\Database\Migrations\CreateAuthTables->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2024-03-28 15:27:51 --> mysqli_sql_exception: Can't create table `crud_data`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `a...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `a...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `a...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `a...')
#4 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Database\Migrations\2017-11-20-223112_create_auth_tables.php(65): CodeIgniter\Database\Forge->createTable('auth_tokens', true)
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): Myth\Auth\Database\Migrations\CreateAuthTables->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2024-03-28 21:58:58 --> mysqli_sql_exception: Can't create table `crud_data`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `a...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `a...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `a...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `a...')
#4 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Database\Migrations\2017-11-20-223112_create_auth_tables.php(65): CodeIgniter\Database\Forge->createTable('auth_tokens', true)
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): Myth\Auth\Database\Migrations\CreateAuthTables->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
INFO - 2024-03-28 22:05:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:05:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:05:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:06:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:06:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:06:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:06:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:06:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:13:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:14:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:14:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:15:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:15:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:16:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:16:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:17:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 22:17:43 --> mysqli_sql_exception: Unknown column 'password_hash' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\codenighter\system\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-03-28 22:17:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 6 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 7 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 22:17:43 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$wKCytd3MULsfMjRdYml4puVK4AiUEF.FxN2m9yHMU7WwxADk9CRAO\', NULL, NULL, NULL, \'ahmad123@gmail.com\', \'ahmad maulana\', \'f985912e5e719391bcacca472806643a\', \'2024-03-28 22:17:43\', \'2024-03-28 22:17:43\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$wKCytd3MULsfMjRdYml4puVK4AiUEF.FxN2m9yHMU7WwxADk9CRAO\', NULL, NULL, NULL, \'ahmad123@gmail.com\', \'ahmad maulana\', \'f985912e5e719391bcacca472806643a\', \'2024-03-28 22:17:43\', \'2024-03-28 22:17:43\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 8 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 9 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 22:17:43 --> [Caused by] mysqli_sql_exception: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$wKCytd3MULsfMjRdYml4puVK4AiUEF.FxN2m9yHMU7WwxADk9CRAO\', NULL, NULL, NULL, \'ahmad123@gmail.com\', \'ahmad maulana\', \'f985912e5e719391bcacca472806643a\', \'2024-03-28 22:17:43\', \'2024-03-28 22:17:43\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$wKCytd3MULsfMjRdYml4puVK4AiUEF.FxN2m9yHMU7WwxADk9CRAO\', NULL, NULL, NULL, \'ahmad123@gmail.com\', \'ahmad maulana\', \'f985912e5e719391bcacca472806643a\', \'2024-03-28 22:17:43\', \'2024-03-28 22:17:43\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$wKCytd3MULsfMjRdYml4puVK4AiUEF.FxN2m9yHMU7WwxADk9CRAO\', NULL, NULL, NULL, \'ahmad123@gmail.com\', \'ahmad maulana\', \'f985912e5e719391bcacca472806643a\', \'2024-03-28 22:17:43\', \'2024-03-28 22:17:43\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 9 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
10 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
INFO - 2024-03-28 22:29:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:29:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-03-28 22:30:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-03-28 22:30:10 --> mysqli_sql_exception: Unknown column 'password_hash' in 'field list' in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\codenighter\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\codenighter\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codenighter\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codenighter\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\codenighter\system\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#8 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#9 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 C:\xampp\htdocs\codenighter\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\codenighter\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\codenighter\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-03-28 22:30:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 6 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 7 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 22:30:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$w8QPURy324y/tWWVqgU4Buqnska6UfsS1Iv7jClr4yawriPzWEODm\', NULL, NULL, NULL, \'ulumf3701@gmail.com\', \'ahmad maulana\', \'4b203e2c913a5bb4cf3a0b3366cedeaa\', \'2024-03-28 22:30:10\', \'2024-03-28 22:30:10\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$w8QPURy324y/tWWVqgU4Buqnska6UfsS1Iv7jClr4yawriPzWEODm\', NULL, NULL, NULL, \'ulumf3701@gmail.com\', \'ahmad maulana\', \'4b203e2c913a5bb4cf3a0b3366cedeaa\', \'2024-03-28 22:30:10\', \'2024-03-28 22:30:10\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 8 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 9 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
CRITICAL - 2024-03-28 22:30:10 --> [Caused by] mysqli_sql_exception: Unknown column 'password_hash' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$w8QPURy324y/tWWVqgU4Buqnska6UfsS1Iv7jClr4yawriPzWEODm\', NULL, NULL, NULL, \'ulumf3701@gmail.com\', \'ahmad maulana\', \'4b203e2c913a5bb4cf3a0b3366cedeaa\', \'2024-03-28 22:30:10\', \'2024-03-28 22:30:10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$w8QPURy324y/tWWVqgU4Buqnska6UfsS1Iv7jClr4yawriPzWEODm\', NULL, NULL, NULL, \'ulumf3701@gmail.com\', \'ahmad maulana\', \'4b203e2c913a5bb4cf3a0b3366cedeaa\', \'2024-03-28 22:30:10\', \'2024-03-28 22:30:10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (\'$2y$10$w8QPURy324y/tWWVqgU4Buqnska6UfsS1Iv7jClr4yawriPzWEODm\', NULL, NULL, NULL, \'ulumf3701@gmail.com\', \'ahmad maulana\', \'4b203e2c913a5bb4cf3a0b3366cedeaa\', \'2024-03-28 22:30:10\', \'2024-03-28 22:30:10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`password_hash`, `reset_hash`, `reset_at`, `reset_expires`, `email`, `username`, `activate_hash`, `created_at`, `updated_at`) VALUES (:password_hash:, :reset_hash:, :reset_at:, :reset_expires:, :email:, :username:, :activate_hash:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 9 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
10 SYSTEMPATH\CodeIgniter.php(941): Myth\Auth\Controllers\AuthController->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\codenighter\\public\\index.php')
ERROR - 2024-03-28 22:38:00 --> mysqli_sql_exception: Can't create table `crud_data`.`auth_tokens` (errno: 150 "Foreign key constraint is incorrectly formed") in C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\codenighter\system\Database\MySQLi\Connection.php(306): mysqli->query('CREATE TABLE `a...', 0)
#1 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `a...')
#2 C:\xampp\htdocs\codenighter\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `a...')
#3 C:\xampp\htdocs\codenighter\system\Database\Forge.php(555): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `a...')
#4 C:\xampp\htdocs\codenighter\vendor\myth\auth\src\Database\Migrations\2017-11-20-223112_create_auth_tables.php(65): CodeIgniter\Database\Forge->createTable('auth_tokens', true)
#5 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(865): Myth\Auth\Database\Migrations\CreateAuthTables->up()
#6 C:\xampp\htdocs\codenighter\system\Database\MigrationRunner.php(181): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\xampp\htdocs\codenighter\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\codenighter\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\codenighter\system\CLI\Console.php(46): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\codenighter\spark(102): CodeIgniter\CLI\Console->run()
#11 {main}
